### ISSUE TITLE
Issue with icons in angular-material 0.9.0-rc2.

### ISSUE THREAD

**Issue by SimeonC** [klarsys/angular-material-icons#15]
I found that all the icons are offset above where they should be in 0.9.0-rc2 (I assume this isn't going to change). The fix I found to get this working properly with angular material is the following CSS snippet:

```css
ng-md-icon {
  fill: currentColor;
  vertical-align: middle;
  display: inline-block;
  line-height: 1;
}
```

This fixes the icon color not being inherited from the text and the bad positioning.

**Comment by AlmaasAre** [comment]
+1

**Comment by djj0809** [comment]
+1, @SimeonC thanks for your work around

**Comment by kevindstanley1988** [comment]
I am not sure if this is a similar issue, but have you tried using an icon from this directive in an input-container like the last form demo on
https://material.angularjs.org/#/demo/material.components.input

if i use this icon i get the icon completely above and not inline at all.
![image](https://cloud.githubusercontent.com/assets/5685997/7498024/ef0b5f3a-f3eb-11e4-9c22-2f390a80d41c.png)

using the following

        <md-content layout-padding>
            <md-input-container class="md-icon-float">
                
                <label>Name</label>
                <ng-md-icon icon="person" style="fill: rgb(56, 71, 160);" size="32" class="name"></ng-md-icon>
                <input ng-model="user.name" type="text">
            </md-input-container>
        </md-content>

**Comment by rcotrina94** [comment]
@kevindstanley1988 same here :(

**Comment by SimeonC** [comment]
From looking at the docs, I think you'll need something along these lines: (I haven't tested this one, this is just the css they use in the docs to do that so you'll probably need to tweak it a bit.)

```css
md-input-container.md-icon-float>ng-md-icon{
    top: 26px;
    left: 2px;
}
md-input-container>ng-md-icon{
    position: absolute;
    top: 5px;
    left: 2px;
}
```

**Comment by rscafi** [comment]
Currently I've copied all rules related to `md-icon`, addapted to `ng-md-icon` and tweaked it a little.
A lot of rules may be unnecessary, but at least I see no bugs.

Hope it helps someone:
https://gist.github.com/rscafi/902eb6b348e4963f0754

**Comment by urmilparikh** [comment]
I have added angular-material-icons.css file compiled from angular-material.css v0.9.7, similar to what @rscafi did. Thank you, @rscafi!

I haven't tested it though. It would help if someone can use it and check for any issues.

**Comment by trevorhreed** [comment]
Using the latest from cdnjs, this is still an issue. However, @SimeonC's solution seems to solve it, so I'm guessing the version on cdnjs is out-of-date?

**Comment by urmilparikh** [comment]
This library does not inject any css automatically, nor have I exported css to CDN yet (since it is untested).
For now, you need to inject .css manually from github (or a local copy).

@SimeonC's solution works, no doubt.
But it may fix one or more specific compatibility issues. The css present in github is expected to fix any/all compatibility issues (and hence, difficult to test all usage scenario).

**Comment by trevorhreed** [comment]
Is there an issue with using the same element name as the Angular Material library (namely md-icon)? That way you could take advantage of the Angular Material CSS.

**Comment by urmilparikh** [comment]
That's possible simply by changing

    .directive('ngMdIcon', function() {

to

    .directive('mdIcon', function() {

in the code.

However, I'm not sure what side-effects it can result.

**Comment by RomFouq** [comment]
I have found an other fix; adding the rule
```css
ng-md-icon svg {
  transform: translate3d(0, 25%, 0);
}
```
seems to fix the vertical alignment problem. I don't know if it's pixel-perfect but this is quite good with 32px icons.

**Comment by QuantumInformation** [comment]
@RomFouq great fix thanks!!

**Comment by RomFouq** [comment]
There is maybe one problem with this fix: the compatibility: http://caniuse.com/#search=translate3d.
It's not supported by IE and Opera Mini, but this directive does not support IE neither, so this is not really a problem.

**Comment by pjdauvert** [comment]
Hi, I've just been through this issue as well.
Running with angular-material 0.10
I made alignment correct changing `vertical-align` to `text-bottom`

```css
ng-md-icon {
    margin: auto;
    background-repeat: no-repeat no-repeat;
    display: inline-block;
    vertical-align: text-bottom;
    fill: currentColor;
    height: 24px;
    width: 24px;
}

Hope this helps.
```
